Issue#5
JaysGitLab/cs-5666-greeting-KaraBeason pull request #10
Opened 2017-02-02 22:45 UTC by KaraBeason

This PR closes #5.  If the command line argument's case is not proper for a name, it will be corrected and printed in the proper case.  There should be no merge conflicts if issue #4 is merged first.

2017-02-03 03:06 UTC, fenwickjb requested changes

2017-02-03 03:06 UTC, fenwickjb commented on Hello.java
> +               name = name.substring(0,1).toUpperCase() + name.substring(1);
This does ensure the first letter is capitalized, but how to know the remainder is not?

2017-02-03 14:13 UTC, KaraBeason commented on Hello.java
> +               name = name.substring(0,1).toUpperCase() + name.substring(1);
I ended up refactoring the code in a later issue so that should take care of this mistake.

2017-02-05 23:57 UTC, KaraBeason commented on Hello.java
> +               name = name.substring(0,1).toUpperCase() + name.substring(1);
I have fixed the code to also ensure the rest of the name is lower case.

2017-02-05 23:58 UTC, merged